hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold : 10
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 60